Simplify citrix launch script

diff --git a/scripts/citrix b/scripts/citrix
--- a/scripts/citrix
+++ b/scripts/citrix
@@ -1,76 +1,34 @@
-#!/usr/bin/env nix-shell
-#! nix-shell -i bash -p citrix_workspace_22_05_0 -p ratpoison -p  xorg.xwininfo
-
+#!/bin/sh
 set -ue
-set -x
-
-shutdown_active() {
-        firejail --list |
-                awk -F: '/name=citrix/ {print $1}' |
-                xargs -i firejail --shutdown={}
-}
-trap shutdown_active EXIT
-
-XHOME=
-
-create_home() {
-        XHOME=$(mktemp --directory)
-        mkdir -p "$XHOME"
-        mkdir -p "$XHOME/.ICAClient"
-        touch "$XHOME/.ICAClient/.eula_accepted"
-}
-
 find_cmd() {
-        cmd=$1
-        found=$(which "$cmd" | xargs readlink -f 2>/dev/null)
-        if [ ! -f "$found" ]; then
-                echo >/dev/stderr "Not found $cmd"
-                exit 1
-        fi
-        echo "$found"
-}
-
-WFICA=$(find_cmd wfica)
-FOUND=$(
-        find "$HOME/Downloads" -name '*.ica' -type f -printf '%T+\t%p\n' |
-                sort -r |
-                head -n 1 |
-                cut -f2
-)
-if [ ! -f "$FOUND" ]; then
-        echo >/dev/stderr "Not found: *.ica"
+    cmd=$1
+    found=$(which "$cmd" | xargs readlink -f 2>/dev/null)
+    if [ ! -f "$found" ]
+    then
+        >/dev/stderr echo "Not found $cmd"
         exit 1
-fi
-
-create_home
-
-cp --verbose "$FOUND" "$XHOME/desktop.ica"
-
-shutdown_active
-
-xwininfo -root
-GEOM=$(
-        xwininfo -root |
-                perl -nE '/-geometry \s+ (\d+)+x(\d+)/x && printf "%dx%d\n", $1 * 0.8, $2 * 0.8'
+    fi
+    echo "$found"
+}
+WFICA=$(find_cmd wfica)
+FOUND=$(find "$HOME/Downloads" -name '*.ica' -type f -printf '%T+\t%p\n' \
+    | sort -r                                                            \
+    | head -n 1                                                          \
+    | cut -f2
 )
-
-firejail \
-        --x11=xephyr \
-        --xephyr-screen="$GEOM" \
-        --name=citrix \
-        --private="$XHOME" \
-        --nosound \
-        --novideo \
-        --private-dev \
-        --machine-id \
-        "$WFICA" "desktop.ica" &
-
-XPID=${!}
-
-while kill -0 "$XPID"; do
-        if firejail --join=citrix ratpoison; then
-                break
-        fi
-done
-
-wait
+if [ ! -f "$FOUND" ]
+then
+    >/dev/stderr echo "Not found: *.ica"
+    exit 1
+fi
+XHOME=$(mktemp --directory)
+mkdir -p "$XHOME"
+mkdir -p "$XHOME/.ICAClient"
+touch "$XHOME/.ICAClient/.eula_accepted"
+cp --verbose "$FOUND" "$XHOME/desktop.ica"
+exec firejail           \
+     --name=citrix      \
+     --private="$XHOME" \
+     --nosound          \
+     --novideo          \
+     "$WFICA" "desktop.ica"
